### ISSUE TITLE
OverflowError: int too long to convert

### ISSUE THREAD

**Issue by entangledloops** [pyglet/pyglet#391]
Sometimes when creating a window, I hit an overflow issue inside `pyglet/window/win32/__init__.py`.

This isn't consistent. If I just rerun a few times, it will mostly work.
Some info about my environment:

Windows 10
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
pyglet 1.5.16

Minimal repro:

```
class Window(pyglet.window.Window):
    def __init__(self):
        super().__init__(1280, 720, vsync=False)

win = Window()
pyglet.app.run()
```

Unfortunately, this error occurs non-deterministically.

![pyglet_exception](https://user-images.githubusercontent.com/3599701/118426497-29e6e900-b680-11eb-9c95-b477a3ac8228.png)

**Comment by benmoran56** [comment]
Thanks for opening the ticket.

My first guess would be that it's a 32/64-bit issue, but you do seem to be already using a 64bit Python build. 
I don't think we've run into this before. To rule out any Python related bugs with 3.7.0, is it possible to give this a try
on a newer Python release? If you can't update the major release, then perhaps 3.7.10?

**Comment by caffeinepills** [comment]
I have seen this only once or twice before in thousands of launches, and it's not reproducible.

Sometimes the `_view_hwnd` returns a crazy long number like 12908519258019200, when normally it's something like 10815522. Unfortunately there is no documentation as to why. According to the win32 docs, any handle returned means it was created successfully. It's possible there was some sort of corruption caused during launch or even that returned value leads to a null. I think this only occurred during a shadow window creation.

The only thing I can recommend is to try to see if Windows will return any sort of error with the `GetLastError` and to add the following before `GetDC` is called.

            _kernel32.GetLastError.restype = DWORD

            print("LAST ERROR", _kernel32.GetLastError())

           print("VIEW HWND", self._view_hwnd, "NOT NULL" if self._view_hwnd else "NULL")
            
            self._dc = _user32.GetDC(self._view_hwnd)

Otherwise there is no much information to go off of.

**Comment by benmoran56** [comment]
Closing now due to lack of reply, but please reopen the ticket if you want to follow up. 

Thank you!

**Comment by entangledloops** [comment]
Let me know if there is any additional info I can provide to help debug. 

Not sure how newer Python would help here; as you mentioned, sounds like something internal to Windows. Even if it works, we can't be sure if it's fixed or if it just happens to work now. 

I sit possible [this workaround](https://github.com/lifting-bits/mcsema/issues/664) is related to the bug?
From `__init__.py` in `libs/win32`:
```
# workaround for win 64-bit, see issue #664
_user32.GetDC.restype = c_void_p # HDC
_user32.GetDC.argtypes = [c_void_p] # [HWND]
```
I wonder if it returns a 64-bit value on my machine, but your native binding only accepts 32-bit inputs at the moment?

**Comment by caffeinepills** [comment]
It should be 64 or 32 bit depending on machine. 

See this code.

```py
class c_void(Structure):
    # c_void_p is a buggy return type, converting to int, so
    # POINTER(None) == c_void_p is actually written as
    # POINTER(c_void), so it can be treated as a real pointer.
    _fields_ = [('dummy', c_int)]


def POINTER_(obj):
    p = ctypes.POINTER(obj)

    # Convert None to a real NULL pointer to work around bugs
    # in how ctypes handles None on 64-bit platforms
    if not isinstance(p.from_param, classmethod):
        def from_param(cls, x):
            if x is None:
                return cls()
            else:
                return x
        p.from_param = classmethod(from_param)

    return p

c_void_p = POINTER_(c_void)
```
It looks like we are overriding c_void_p with our own overridden one due to various bugs. I am not sure when these were implemented. It's possible ctypes has very buggy implementations back in the day when 32 and 64 bit versions exist. It's possible those issues were fixed and are now causing more harm than good. 

However, removing this may require extensive testing to make sure nothing breaks in the process.

**Comment by benmoran56** [comment]
It's pretty likely that that void pointer workaround is no longer necessary, so we should probably look int that at some point. 

@entangledloops As I mentioned earlier, I would definitely suggest upgrading your Python version as well, just to rule out possible bugs. There have been a ton of ctypes bugs fixed since the 3.7.0 release, even in the 3.7 series.

**Comment by benmoran56** [comment]
Closing due to age, but please follow up if you still have issues with recent Python releases.

**Comment by Whiax** [comment]
Hi! Same issue with python 3.13.1, windows 10, pyglet 2.1.2 (not the latest version).


```
  File \pyglet\window\__init__.py:576 in __init__
    self._create()

  File \pyglet\window\win32\__init__.py:264 in _create
    self._dc = _user32.GetDC(self._view_hwnd)

ArgumentError: argument 1: OverflowError: int too long to convert

```

I may think it's a temporary state in Windows as I had this issue 2~3 times during few minutes (it was still random), and now I don't think I can reproduce it again. It's not a big issue but it can still happen and it looks like it's very random.

**Comment by benmoran56** [comment]
@Whiax there were many small fixes, some related to Windowing on win32 in the later point releases. 
It's highly recommended to upgrade to the latest pyglet release. There shouldn't be any major changes in the point releases.

**Comment by justinsavage35** [comment]
Hi, 

I am getting the same issue regularly.

System information:
Python: 3.11.9
Platform: Windows-10-10.0.17763-SP0
Pyglet: 1.5.31
Vendor ([pyglet.gl](http://pyglet.gl/).gl_info.get_vendor()): Mesa
Renderer ([pyglet.gl](http://pyglet.gl/).gl_info.get_renderer()): llvmpipe (LLVM 13.0.1, 256 bits)
Version ([pyglet.gl](http://pyglet.gl/).gl_info.get_version()): 4.5 (Compatibility Profile) Mesa 24.1.0 (git-7f68491319)


```
Error message:
Traceback (most recent call last):
  File , line 105, in export_png_from_mesh
    png = scene.save_image(
          ^^^^^^^^^^^^^^^^^
  File "\Lib\site-packages\trimesh\scene\scene.py", line 964, in save_image
    png = render_scene(
          ^^^^^^^^^^^^^
  File "\Lib\site-packages\trimesh\viewer\windowed.py", line 892, in render_scene
    window = SceneViewer(
             ^^^^^^^^^^^^
  File "\Lib\site-packages\trimesh\viewer\windowed.py", line 191, in __init__
    super(SceneViewer, self).__init__(config=window_conf,
  File "\site-packages\pyglet\window\win32\__init__.py", line 136, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "\Lib\site-packages\pyglet\window\__init__.py", line 659, in __init__
    self._create()
  File "\site-packages\pyglet\window\win32\__init__.py", line 241, in _create
    self._dc = _user32.GetDC(self._view_hwnd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 1: OverflowError: int too long to convert
```
The print statements above have been added to the code.

LAST ERROR 0
VIEW HWND 18446744072222605706
NOT NULL
HWND 928448822
Due to the trimesh dependency of pyglet < 2, I am unable to upgrade further than 1.5.31.

I understand the issue is coming from:

```
self._view_hwnd = _user32.CreateWindowExW(
                0,
                self._view_window_class.lpszClassName,
                u'',
                WS_CHILD | WS_VISIBLE,
                0, 0, 0, 0,
                self._hwnd,
                0,
                self._view_window_class.hInstance,
                0)
```

With _user32.CreateWindowExW generating a view handle to a window over 2**32 but why is this happening?

Please let me know if you need any more information. Would it be possible to get an estimate for a quick fix?

Script below

```
import math
import os
import platform
import subprocess
from pathlib import Path
from typing import Union

import numpy as np
import trimesh
import pyglet

from pyglet import gl


if platform.system() == "Windows":
    os.environ["XVFB_WHD"] = "1920x1080x24"
    os.environ["DISPLAY"] = ":0"
    os.environ["LIBGL_ALWAYS_SOFTWARE"] = "true"
    os.environ["GALLIUM_DRIVER"] = "softpipe"


IMAGE_DIR = "./images"



print("Python:", platform.python_version())
print("Platform:", platform.platform())
print("pyglet:", pyglet.version)
print("Vendor:",
          gl.gl_info.get_vendor())
print("Renderer:",
          gl.gl_info.get_renderer())
print("Version:",
          gl.gl_info.get_version())

try:
    print("Vendor:",
          gl.gl_info.get_vendor())
    print("Renderer:",
          gl.gl_info.get_renderer())
    print("Version:",
          gl.gl_info.get_version())
except Exception as e:
    print("Failed to query OpenGL:", e)

def export_png_from_mesh(
    mesh: Union[trimesh.base.Trimesh, trimesh.Scene],
    png_file_path: Path,
    obj_file_path: Union[Path, None] = None,
    is_part_delta: bool = False,
) -> bool:
    #mesh.visual.vertex_colors = trimesh.visual.random_color()

    scene = trimesh.Scene()
    scene.add_geometry(mesh)
    bounds = scene.bounds
    corners = trimesh.bounds.corners(bounds)
    r_e = trimesh.transformations.euler_matrix(
        math.radians(45),
        math.radians(45),
        math.radians(45),
        "ryxz",
    )
    t_r = scene.camera.look_at(corners, rotation=r_e)
    scene.camera_transform = t_r
    
    

    try:    
        display = pyglet.canvas.get_display()
        screen = display.get_default_screen()
        window_conf = screen.get_best_config(
        pyglet.gl.Config(double_buffer=True, depth_size=24)
        )
        
        png = scene.save_image(
            resolution=[640, 480],
            visible=True,
            window_conf=window_conf,
            flags={"cull": False},
        )
        with open(png_file_path, "wb") as f:
            f.write(png)
            f.close()

        return True

    except Exception as e:
        print(f"unable to save image: {type(e)}: {str(e)}")
        return False
        

if __name__ == "__main__":
    
    mesh = trimesh.primitives.Sphere(radius=1.0, center=None, transform=None, subdivisions=3, mutable=True)
    image_path = Path(IMAGE_DIR)
    image_path.mkdir(exist_ok=True)    
        
    for i in range(15000):
        export_png_from_mesh(mesh, image_path / f"sphere_{i}.png")

```

**Comment by caffeinepills** [comment]
I will take a look at this to see if I can replicate with trimesh.

**Comment by caffeinepills** [comment]
@justinsavage35 Unfortunately, I ran your example, but I was unable to get it to error. What version of trimesh are you using? Also does adding this to the top of your script fix the issue?
```py
import pyglet
pyglet.options["shadow_window"] = False
```

**Comment by justinsavage35** [comment]
trimesh==3.23.5 is being used. I'll try

```
import pyglet
pyglet.options["shadow_window"] = False
```

**Comment by caffeinepills** [comment]
> trimesh==3.23.5 is being used. I'll try
> 
> ```
> import pyglet
> pyglet.options["shadow_window"] = False
> ```

Did this improve it at all?

**Comment by justinsavage35** [comment]
Hi, apologies for the delayed response. I have limited access to the machine on which the issue is occurring. I will post as soon as I have the logs.
